name: Blocked Issue Labeler

on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  add-blocked-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Add blocked label if issue is blocked
        run: |
          body=$BODY
          comment=$COMMENT
          issue_number=${{ github.event.issue.number }}

          # if body contains "blocked" or comment contains "blocked"
          # add label "blocked"

          if [[ "${body,,}" == *"blocked"* ]] || [[ "${comment,,}" == *"blocked"* ]]; then
            echo "Issue is blocked"
            echo "Adding blocked label"
            gh issue edit $issue_number --add-label blocked
          fi
        env:
          BODY: ${{ github.event.issue.body }}
          COMMENT: ${{ github.event.comment.body }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}