name: Deploy Develop Branch

on:
  push:
    branches:
      - develop
    paths:
      - 'src/**'
      - 'test/**'
      - '**.sln'
      - '**.cake'
      - '.github/workflows/branch-develop.yml'
      - '.github/workflows/step-*.yml'
  workflow_dispatch:

permissions:
  contents: write
  workflows: write

jobs:
  get-version:
    uses: ./.github/workflows/step-version.yml
    with:
      is-pre-release: true

  build:
    needs: [ get-version ]
    uses: ./.github/workflows/step-build.yml
    with:
      version: ${{ needs.get-version.outputs.version }}
      checkout-ref: ${{ github.base_ref }}

  publish-to-nuget:
    needs: [ get-version,build ]
    uses: ./.github/workflows/step-publish.yml
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
    with:
      deploy-env: nuget-beta
      deploy-branch: ${{ github.base_ref }}
      version: ${{ needs.get-version.outputs.version }}
  
  tag-release:
    needs: [ get-version,publish-to-nuget ]
    uses: ./.github/workflows/step-tag-release.yml
    with:
      version: ${{ needs.get-version.outputs.version }}