on:
  workflow_call:
    inputs:
      comparison:
        type: string
        description: 'The comparison to use for the mutation testing'
        required: true
env:
  MAJOR_DOTNET_VERSION: 8
  TestPath: /home/runner/work/Html2Markdown/Html2Markdown/test/Html2Markdown.Test/Files/
  STRYKER_VERSION: 4.8.1
        
jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
        with:
          dotnet-version: ${{ env.MAJOR_DOTNET_VERSION }}.0.x
      - name: Install Stryker
        run: |
          dotnet tool install -g dotnet-stryker --version $STRYKER_VERSION
      - name: Run Stryker
        env:
          COMPARISON: ${{ inputs.comparison }}
        run: |
          dotnet stryker --since:$COMPARISON
      - name: Upload Report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: Mutation-Report
          path: ./StrykerOutput/*/reports/mutation-report.html